# -*- coding: utf-8 -*-
"""Final_one_lstm(structured)_updated environment types analysis included.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMYA--XlfzEh6GJ_T2sPVi-R1XQLaqag

##Importing libraries
"""

!pip install -q umap-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
import umap
from statsmodels.formula.api import ols
import statsmodels.api as sm
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping
import random
import os

"""##Global Variables"""

RANDOM_SEED = 42
MAX_SEQUENCE_LENGTH = 200
BATCH_SIZE = 16
LATENT_DIM = 32
LSTM_UNITS = 128
EPOCHS = 100
N_CLUSTERS = 3  # Fixed at 3 as requested

"""##Seeding"""

# Set seeds for reproducibility
def set_seeds(seed=RANDOM_SEED):
    """Set seeds for reproducibility across all libraries"""
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)
    tf.config.experimental.enable_op_determinism()

set_seeds()

"""##Load and Preprocess Data"""

#Load and pre processing the data
def load_and_preprocess_data(file_path):
    """Load and preprocess the game data"""
    df = pd.read_csv("/content/Complete game data csv(modified envo)38participents.csv")
    print(f"[INFO] Loaded dataset with shape: {df.shape}") #Debugging

    # Process Environment_Type
    le = LabelEncoder()
    df['Environment_Type'] = le.fit_transform(df['Environment_Type'])
    print("[INFO] Environment Type mapping:", dict(zip(le.classes_, le.transform(le.classes_)))) #Debugging

    # Handle Win-Stay column
    df = df.dropna(subset=["Win-Stay"])
    df["Win-Stay"] = df["Win-Stay"].astype(int)
    print(f"[INFO] After dropping NaNs, dataset shape: {df.shape}") #Debugging

    # Sort by participant
    df = df.sort_values(["Participant"])
    df
    return df

"""##Data Visualisation"""

def explore_dataset(df):
    """Print missing value summary, descriptive statistics, and show basic visualizations"""

    print("\n\n\n--- Missing Values ---")
    print(df.isnull().sum())

    print("\n\n\n--- Descriptive Statistics ---")
    print(df.describe(include='all'))

    # Visualizations
    print("\n\n\n--- Generating Visualizations ---")

    # Distribution plots for numerical features
    numeric_cols = df.select_dtypes(include=['number']).columns.tolist()

    for col in numeric_cols:
        plt.figure(figsize=(8, 4))
        sns.histplot(df[col].dropna(), kde=True, bins=30)
        plt.title(f'Distribution of {col}')
        plt.xlabel(col)
        plt.ylabel('Frequency')
        plt.grid(True)
        plt.tight_layout()
        plt.show()

    # Count plots for categorical features
    categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
    for col in categorical_cols:
        plt.figure(figsize=(8, 4))
        sns.countplot(data=df, x=col, order=df[col].value_counts().index)
        plt.title(f'Count Plot of {col}')
        plt.xlabel(col)
        plt.ylabel('Count')
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

"""##Normalisation of Features"""

#Normalisation of Features
def normalize_features(df, features_to_use):
    """Normalize the selected features"""
    scaler = MinMaxScaler()
    df_norm = df.copy()
    df_norm[features_to_use] = scaler.fit_transform(df[features_to_use])
    print("[INFO] Normalized features with MinMaxScaler.")  #Debugging
    print(df_norm[features_to_use].head())                   #Debugging
    return df_norm

"""##Creating Sequences"""

#Creating Sequences
def create_sequences(df_norm, features_to_use, max_len=MAX_SEQUENCE_LENGTH):
    """Create fixed-length sequences for each participant"""
    participant_sequences = {}
    participant_ids = []

    for pid, group in df_norm.groupby("Participant"):
        sequence = group[features_to_use].to_numpy()
        participant_sequences[pid] = sequence
        participant_ids.append(pid)

    # Get number of features
    num_features = len(features_to_use)

    print(f"[INFO] Total participants: {len(participant_ids)}") #Debugging


    # Prepare fixed-length sequences
    fixed_sequences = []
    for pid in participant_ids:
        seq = participant_sequences[pid]
        if len(seq) >= max_len:
            trimmed_seq = seq[:max_len]  # Trim
        else:
            # Pad with zeros
            padding = np.zeros((max_len - len(seq), num_features))
            trimmed_seq = np.vstack([seq, padding])
        fixed_sequences.append(trimmed_seq)

    # Convert to final 3D numpy array: (n_participants, sequence_length, n_features)
    sequence_array = np.stack(fixed_sequences)

    print(f"Created sequences with shape: {sequence_array.shape}")

    return sequence_array, participant_ids

"""##LSTM Autoencoder"""

#LSTM autoencoder
def build_lstm_autoencoder(timesteps, n_features, latent_dim=LATENT_DIM, lstm_units=LSTM_UNITS):
    """Build LSTM autoencoder model"""
    # Encoder
    encoder_inputs = layers.Input(shape=(timesteps, n_features), name='encoder_input')

    # Add dropout for regularization
    x = layers.Dropout(0.2)(encoder_inputs)

    # First LSTM layer with return_sequences=True
    x = layers.LSTM(lstm_units // 2, return_sequences=True,
                   kernel_regularizer=tf.keras.regularizers.l2(1e-4),
                   name='lstm_1')(x)

    x = layers.Dropout(0.2)(x)

    # Second LSTM layer
    encoded = layers.LSTM(lstm_units, return_sequences=False, name='lstm_2')(x)

    # Dense bottleneck layer (latent representation)
    latent = layers.Dense(latent_dim, activation='relu', name='latent_encoding',
                         kernel_regularizer=tf.keras.regularizers.l2(1e-4))(encoded)

    # Decoder
    repeated = layers.RepeatVector(timesteps, name='repeat_vector')(latent)

    # LSTM decoder layers
    x = layers.LSTM(lstm_units, return_sequences=True, name='lstm_decoder_1')(repeated)
    x = layers.Dropout(0.2)(x)
    x = layers.LSTM(lstm_units // 2, return_sequences=True, name='lstm_decoder_2')(x)

    # Output layer
    decoder_outputs = layers.TimeDistributed(
        layers.Dense(n_features, name='dense_output')
    )(x)

    # Define models
    autoencoder = models.Model(encoder_inputs, decoder_outputs, name='autoencoder')
    encoder = models.Model(encoder_inputs, latent, name='encoder')
    #########
    autoencoder, encoder
    return autoencoder, encoder

"""##Creating Tensorflow Dataset"""

#Create Tensorflow dataset
def create_tf_dataset(sequence_array, batch_size=BATCH_SIZE):
    """Create TensorFlow Dataset for efficient training"""
    # Create dataset
    dataset = tf.data.Dataset.from_tensor_slices((sequence_array, sequence_array))

    # Shuffle, batch, and prefetch
    dataset = dataset.shuffle(buffer_size=len(sequence_array), seed=RANDOM_SEED)
    dataset = dataset.batch(batch_size)
    dataset = dataset.prefetch(tf.data.AUTOTUNE)
    dataset
    return dataset

"""##Training autoencoder"""

#Training autoencoder
def train_autoencoder(autoencoder, dataset, epochs=EPOCHS):
    """Train the autoencoder model"""
    # Define callbacks
    callbacks = [
        EarlyStopping(monitor='loss', patience=10, restore_best_weights=True, verbose=1)
    ]

    # Compile model with Adam optimizer and MSE loss
    autoencoder.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss='mse'
    )

    # Train model
    history = autoencoder.fit(
        dataset,
        epochs=epochs,
        callbacks=callbacks,
        verbose=1
    )

    # Plot training loss
    plt.figure(figsize=(10, 6))
    plt.plot(history.history['loss'])
    plt.title('Model Loss During Training')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.grid(True)
    plt.show()

    return autoencoder

"""##Performing Dimensionality Reduction"""

#Perform dimensionality Reduction
def perform_dimensionality_reduction(embeddings, method='both'):
    """Perform dimensionality reduction using t-SNE and/or UMAP"""
    results = {}

    if method in ['tsne', 'both']:
        tsne = TSNE(n_components=2, perplexity=5, random_state=RANDOM_SEED)
        results['tsne'] = tsne.fit_transform(embeddings)
        print("t-SNE reduction completed")

    if method in ['umap', 'both']:
        reducer = umap.UMAP(n_neighbors=15, min_dist=0.1, random_state=RANDOM_SEED)
        results['umap'] = reducer.fit_transform(embeddings)
        print("UMAP reduction completed")
    return results

"""##Perform clustering"""

#Perform Clustering
def perform_clustering(reduced_embeddings):
    """Perform clustering on reduced embeddings"""
    clustering_results = {}

    # Fixed at 3 clusters as requested
    kmeans = KMeans(n_clusters=N_CLUSTERS, random_state=RANDOM_SEED, n_init=10)

    for dim_method, embeddings_2d in reduced_embeddings.items():
        labels = kmeans.fit_predict(embeddings_2d)
        clustering_results[dim_method] = labels
        print(f"Clustering completed for {dim_method}")

    return clustering_results

"""##Visualizing Clusters

"""

#Visualizing Clusters
def visualize_clusters(embeddings_2d, labels, participant_ids, method_name):
    """Visualize clustering results"""
    plt.figure(figsize=(12, 10))
    scatter = plt.scatter(embeddings_2d[:, 0], embeddings_2d[:, 1],
                         c=labels, cmap='viridis', s=100)

    plt.title(f"Participant Clusters via LSTM + {method_name.upper()}", fontsize=14)
    plt.xlabel(f"{method_name.upper()} 1", fontsize=12)
    plt.ylabel(f"{method_name.upper()} 2", fontsize=12)
    plt.colorbar(scatter, label="Cluster ID")
    plt.grid(True, alpha=0.3)

    # Annotate each point with the Participant ID
    for i, participant in enumerate(participant_ids):
        plt.text(embeddings_2d[i, 0] + 0.2, embeddings_2d[i, 1] + 0.2,
                participant, fontsize=9, alpha=0.8)

    plt.tight_layout()
    plt.show()

"""##Analazing clusters"""

#Analyzeing clusters
def analyze_clusters(df, participant_ids, labels, time_features):
    """Analyze clusters and their characteristics"""
    # Create a DataFrame with participant IDs and their cluster labels
    labels_df = pd.DataFrame({
        "Participant": participant_ids,
        "Cluster": labels
    })

    # Map clusters to behavior types
    labels_df["Behavior_Type"] = labels_df["Cluster"].map({
        0: "group_1",#"Explorers",
        1: "group_2",#"Exploiters",
        2: "group_3"#"Balanced"
    })

    # Display cluster assignments
    print("\n--- Participant Cluster Assignments ---")
    print(labels_df)

    # Merge with original df
    df_labeled = df.merge(labels_df, on="Participant")

    # Summary statistics by cluster
    cluster_stats = df_labeled.groupby("Behavior_Type")[time_features].mean()
    print("\n--- Cluster Characteristics ---")
    print(cluster_stats)

    # Visualization of features over time by cluster
    for feature in time_features:
        plt.figure(figsize=(10, 6))
        sns.lineplot(data=df_labeled, x="Trial", y=feature,
                    hue="Behavior_Type", errorbar='se' , estimator="mean")
        plt.title(f"{feature} Over Time by Cluster")
        plt.xlabel("Trial")
        plt.ylabel(feature)
        plt.legend(title="Behavior Type")
        plt.grid(True)
        plt.show()

    return df_labeled

# #Anlalysis based on environment type


def analyze_cluster_performance_by_environment(df, performance_metrics=None, participant_col='Participant', cluster_col='Cluster', behavior_col='Behavior_Type', env_col='Environment_Type'):
    """
    Analyze and visualize how each cluster (group) performs across different environment types.

    Parameters:
    - df (pd.DataFrame): Dataset with participant, cluster assignments, behavior type, and environment types
    - performance_metrics (list): List of columns to use as performance metrics, defaults to ['Score', 'Reward']
    - participant_col (str): Column name for participants
    - cluster_col (str): Column name for cluster assignments (group)
    - behavior_col (str): Column name for behavior type
    - env_col (str): Column name for environment types

    Returns:
    - summary_df (dict): Summary of performance statistics for each cluster in each environment
    - anova_results (dict): ANOVA results for cluster and environment interaction
    """

    # Default performance metrics
    if performance_metrics is None:
        performance_metrics = ['Score', 'Reward']

    # Create a mapping for Environment_Type to original environment names
    #'High-Fast': np.int64(0), 'High-Slow': np.int64(1), 'Low-Fast': np.int64(2), 'Low-Slow': np.int64(3)
    #[INFO] Environment Type mapping: {'High-Fast': np.int64(0), 'High-Slow': np.int64(1), 'Low-Fast': np.int64(2), 'Low-Slow': np.int64(3)}
    env_names = {
        0: "High-Fast",
        1: "High-Slow",
        2: "Low-Fast",
        3: "Low-Slow"
    }

    # Create a copy of df with environment names
    df_with_env_names = df.copy()
    df_with_env_names['Environment_Name'] = df_with_env_names[env_col].map(env_names)

    summary_dfs = {}
    anova_results = {}

    for perf_col in performance_metrics:
        print(f"\n\n--- Analysis for {perf_col} ---\n")

        # Step 1: Descriptive statistics with environment names
        descriptive_stats = df_with_env_names.groupby([behavior_col, 'Environment_Name'])[perf_col].describe()
        print("\nDescriptive Statistics by Cluster and Environment:\n")
        print(descriptive_stats)

        # Step 2: Compute mean and standard deviation for each cluster in each environment
        summary_df = df_with_env_names.groupby([behavior_col, 'Environment_Name'])[perf_col].agg(['mean', 'std', 'count']).reset_index()
        summary_df.rename(columns={'mean': f'Average_{perf_col}', 'std': f'StdDev_{perf_col}', 'count': 'Count'}, inplace=True)

        print("\nSummary of Mean and StdDev for each Cluster:\n")
        print(summary_df)

        summary_dfs[perf_col] = summary_df

        # Step 3: Visualizations with environment names
        # Barplot
        plt.figure(figsize=(12, 6))
        sns.barplot(
            data=df_with_env_names,
            x='Environment_Name',
            y=perf_col,
            hue=behavior_col,
            errorbar='se',  # Use newer parameter instead of deprecated ci
            palette='Set2'
        )
        plt.title(f'{perf_col} Comparison Across Clusters and Environments', fontsize=14)
        plt.xlabel('Environment Type', fontsize=12)
        plt.ylabel(perf_col, fontsize=12)
        plt.legend(title='Behavior Type')
        plt.tight_layout()
        plt.grid(True, axis='y', linestyle='--', alpha=0.6)
        plt.show()

        # Boxplot
        plt.figure(figsize=(12, 6))
        sns.boxplot(
            data=df_with_env_names,
            x='Environment_Name',
            y=perf_col,
            hue=behavior_col,
            palette='Set2'
        )
        plt.title(f'{perf_col} Distribution Across Clusters and Environments', fontsize=14)
        plt.xlabel('Environment Type', fontsize=12)
        plt.ylabel(perf_col, fontsize=12)
        plt.legend(title='Behavior Type')
        plt.tight_layout()
        plt.show()

        # Step 4: ANOVA Analysis (still using numeric env_col for statistical analysis)
        try:
            # For the Win-Stay column ANOVA (add this inside the try block)
            if perf_col == "Win-Stay":
                # Formula needs to handle hyphenated name
                model = ols(f'`{perf_col}` ~ C({behavior_col}) * C({env_col})', data=df).fit()
                anova_table = sm.stats.anova_lm(model, typ=2)
            else:
                model = ols(f'{perf_col} ~ C({behavior_col}) * C({env_col})', data=df).fit()
                anova_table = sm.stats.anova_lm(model, typ=2)

            print("\nANOVA Analysis Results:\n")
            print(anova_table)

            anova_results[perf_col] = anova_table
        except Exception as e:
            print(f"Error in ANOVA analysis for {perf_col}: {str(e)}")
            anova_results[perf_col] = None

    return summary_dfs, anova_results

def analyze_performance_by_volatility(df, performance_metrics=None, participant_col='Participant',
                                     behavior_col='Behavior_Type', env_col='Environment_Type'):
    """
    Analyze and visualize how each cluster (group) performs across high and low volatility environments.

    Parameters:
    - df (pd.DataFrame): Dataset with participant, cluster assignments, behavior type, and environment types
    - performance_metrics (list): List of columns to use as performance metrics
    - participant_col (str): Column name for participants
    - behavior_col (str): Column name for behavior type
    - env_col (str): Column name for environment types

    Returns:
    - summary_dfs (dict): Summary of performance statistics for each cluster in each volatility level
    - anova_results (dict): ANOVA results for cluster and volatility level interaction
    """

    # Default performance metrics if none provided
    if performance_metrics is None:
        performance_metrics = ['Score', 'Reward', 'Response_Time', 'Win-Stay', 'Exploration', 'Exploitation']

    # Create a copy of df
    df_volatility = df.copy()

    # Create volatility column based on Environment_Type
    # High Volatile: 'High-Fast' (0) and 'Low-Fast' (2)
    # Low Volatile: 'High-Slow' (1) and 'Low-Slow' (3)
    #[INFO] Environment Type mapping: {'High-Fast': np.int64(0), 'High-Slow': np.int64(1), 'Low-Fast': np.int64(2), 'Low-Slow': np.int64(3)}

    volatility_mapping = {
        0: "High Volatility",  # High-Fast
        1: "Low Volatility",   # High-Slow
        2: "High Volatility",  # Low-Fast
        3: "Low Volatility"    # Low-Slow
    }

    df_volatility['Volatility_Level'] = df_volatility[env_col].map(volatility_mapping)

    summary_dfs = {}
    anova_results = {}

    for perf_col in performance_metrics:
        print(f"\n\n--- Volatility Analysis for {perf_col} ---\n")

        # Step 1: Descriptive statistics with volatility levels
        descriptive_stats = df_volatility.groupby([behavior_col, 'Volatility_Level'])[perf_col].describe()
        print("\nDescriptive Statistics by Cluster and Volatility Level:\n")
        print(descriptive_stats)

        # Step 2: Compute mean and standard deviation for each cluster in each volatility level
        summary_df = df_volatility.groupby([behavior_col, 'Volatility_Level'])[perf_col].agg(['mean', 'std', 'count']).reset_index()
        summary_df.rename(columns={'mean': f'Average_{perf_col}', 'std': f'StdDev_{perf_col}', 'count': 'Count'}, inplace=True)
        print("\nSummary of Mean and StdDev for each Cluster by Volatility Level:\n")
        print(summary_df)

        summary_dfs[perf_col] = summary_df

        # Step 3: Visualizations with volatility levels
        # Barplot
        plt.figure(figsize=(12, 6))
        sns.barplot(
            data=df_volatility,
            x='Volatility_Level',
            y=perf_col,
            hue=behavior_col,
            errorbar='se',
            palette='Set2'
        )
        plt.title(f'{perf_col} Comparison Across Clusters and Volatility Levels', fontsize=14)
        plt.xlabel('Volatility Level', fontsize=12)
        plt.ylabel(perf_col, fontsize=12)
        plt.legend(title='Behavior Type')
        plt.tight_layout()
        plt.grid(True, axis='y', linestyle='--', alpha=0.6)
        plt.show()

        # Boxplot
        plt.figure(figsize=(12, 6))
        sns.boxplot(
            data=df_volatility,
            x='Volatility_Level',
            y=perf_col,
            hue=behavior_col,
            palette='Set2'
        )
        plt.title(f'{perf_col} Distribution Across Clusters and Volatility Levels', fontsize=14)
        plt.xlabel('Volatility Level', fontsize=12)
        plt.ylabel(perf_col, fontsize=12)
        plt.legend(title='Behavior Type')
        plt.tight_layout()
        plt.show()

        # Step 4: ANOVA Analysis for volatility
        try:
            # Create a numeric volatility column for ANOVA
            df_volatility['Volatility_Numeric'] = df_volatility['Volatility_Level'].map({"High Volatility": 1, "Low Volatility": 0})

            if perf_col == "Win-Stay":
                # Formula needs to handle hyphenated name
                model = ols(f'`{perf_col}` ~ C({behavior_col}) * C(Volatility_Numeric)', data=df_volatility).fit()
            else:
                model = ols(f'{perf_col} ~ C({behavior_col}) * C(Volatility_Numeric)', data=df_volatility).fit()

            anova_table = sm.stats.anova_lm(model, typ=2)
            print("\nANOVA Analysis Results for Volatility Effect:\n")
            print(anova_table)
            anova_results[perf_col] = anova_table

        except Exception as e:
            print(f"Error in ANOVA analysis for {perf_col}: {str(e)}")
            anova_results[perf_col] = None

        # Step 5: Calculate and display the difference between high and low volatility for each group
        pivot_table = df_volatility.pivot_table(
            index=behavior_col,
            columns='Volatility_Level',
            values=perf_col,
            aggfunc='mean'
        )

        if "High Volatility" in pivot_table.columns and "Low Volatility" in pivot_table.columns:
            pivot_table['Difference'] = pivot_table["High Volatility"] - pivot_table["Low Volatility"]
            pivot_table['Percent_Change'] = (pivot_table['Difference'] / pivot_table["Low Volatility"]) * 100

            print("\nDifference in Performance Between Volatility Levels:\n")
            print(pivot_table)

            # Visualize the difference
            plt.figure(figsize=(10, 6))
            pivot_table['Difference'].plot(kind='bar', color='skyblue')
            plt.title(f'Difference in {perf_col} Between High and Low Volatility', fontsize=14)
            plt.xlabel('Behavior Type', fontsize=12)
            plt.ylabel(f'Difference in {perf_col}', fontsize=12)
            plt.grid(True, axis='y', linestyle='--', alpha=0.6)
            plt.tight_layout()
            plt.show()

    return summary_dfs, anova_results, df_volatility

"""## Main Section"""



# Main function to run the entire pipeline
def main():
    # Load and preprocess data
    file_path = "/content/Complete game data csv(modified envo)38participents.csv"  # Update this path as needed
    print(f"Loading data from {file_path}")
    df = load_and_preprocess_data(file_path)

    # Define features
    time_features = ["Reward", "Score", "Win-Stay", "Lose-Shift",
                    "Exploration", "Exploitation", "Response_Time"]

    features_to_use = [
        "Environment", "Environment_Type", "Chosen_Island", "Probability",
        "Random_Value", "Reward", "Score", "Response_Time", "Lose-Shift",
        "Exploration", "Exploitation", "Win-Stay"
    ]

    #Data Visualisation
    explore_dataset(df)

    # Normalize features
    df_norm = normalize_features(df, features_to_use)

    # Create sequences
    sequence_array, participant_ids = create_sequences(df_norm, features_to_use)

    # Create TensorFlow dataset
    dataset = create_tf_dataset(sequence_array)

    # Build model
    timesteps = sequence_array.shape[1]
    n_features = sequence_array.shape[2]
    autoencoder, encoder = build_lstm_autoencoder(timesteps, n_features)

    # Summarize model architecture
    autoencoder.summary()

    # Train autoencoder
    trained_autoencoder = train_autoencoder(autoencoder, dataset)

    # Generate embeddings
    embeddings = encoder.predict(sequence_array)
    print("Generated embeddings with shape:", embeddings.shape)

    # Dimensionality reduction (both t-SNE and UMAP)
    reduced_embeddings = perform_dimensionality_reduction(embeddings)

    # Clustering
    clustering_results = perform_clustering(reduced_embeddings)

    # Visualize clusters
    for method, embeddings_2d in reduced_embeddings.items():
        visualize_clusters(embeddings_2d, clustering_results[method],
                          participant_ids, method)

    # Analyze clusters (using t-SNE results for analysis)
    df_labeled = analyze_clusters(df, participant_ids,
                                 clustering_results['tsne'], time_features)

    # # Assuming df is already created and has relevant columns
    # performance_summary, anova_results = analyze_cluster_performance_by_environment(df_labeled)
    # # Print the performance summary and ANOVA results
    # print(" Performance Summary:")
    # print(performance_summary)

    # print("\n ANOVA Results:")
    # print(anova_results)

    # print("Analysis complete!")
    # Analyze performance by environment
    print("\n--- Analyzing Performance by Environment Type ---")
    performance_metrics = ["Score", "Reward", "Response_Time", "Win-Stay", "Exploration", "Exploitation"]
    performance_summary, anova_results = analyze_cluster_performance_by_environment(df_labeled, performance_metrics=performance_metrics)

    # Analyze performance by volatility level
    print("\n--- Analyzing Performance by Volatility Level ---")
    volatility_summary, volatility_anova, df_with_volatility = analyze_performance_by_volatility(
        df_labeled,
        performance_metrics=["Score", "Reward", "Response_Time", "Win-Stay", "Exploration", "Exploitation"])


    return df_labeled



if __name__ == "__main__":
    df_labeled = main()